# Generated by Django 5.1.7 on 2025-03-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_rename_blogger_bloggermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloggermodel',
            old_name='blogger',
            new_name='is_blogger',
        ),
    ]
