# Generated by Django 5.1.7 on 2025-03-12 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0005_commentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='BloggerModel',
            new_name='Blogger',
        ),
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
