# Generated by Django 5.1.7 on 2025-03-12 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0006_rename_blogmodel_blog_rename_bloggermodel_blogger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogger',
            new_name='Profile',
        ),
    ]
